import jdk.jfr.BooleanFlag;

import javax.persistence.*;
import java.sql.Blob;
import java.time.LocalDate;

@Entity
@Table(name = "Persons")
public class Person {
    @Id
    @GeneratedValue //autogenerated?
    @Column(name = "ID")
    private int id;

    @Column(name = "VERSION")
    private long version;
    @Column(name = "FIRST_NAME", length = 40)
    private String firstName;
    @Column(name = "LAST_NAME", length = 40)
    private String lastName;

    @Column(name = "BIRTHDAY")
    private LocalDate birthDay;

    @Column(name = "GENDER", length = 10)
    @Enumerated(EnumType.STRING)
    private GenderType gender;

    @Lob
    @Column(name = "PICTURE")
    private Blob picture;

    @Lob
    @Column(name = "COMMNT")
    private String comment;

    @BooleanFlag
    @Column(name = "MARRIED")
    private boolean married;

    private int age;

    @Column(name = "HOMEPAGE", length = 255)
    private String homepage;

    public Person() {
    }

    public Person(long version, String firstName, String lastName, LocalDate birthDay, GenderType gender, Blob picture, String comment, boolean married, int age, String homepage) {
        this.version = version;
        this.firstName = firstName;
        this.lastName = lastName;
        this.birthDay = birthDay;
        this.gender = gender;
        this.picture = picture;
        this.comment = comment;
        this.married = married;
        this.age = age;
        this.homepage = homepage;
    }

    public long getVersion() {
        return version;
    }

    public Person setVersion(long version) {
        this.version = version;
        return this;
    }

    public String getFirstName() {
        return firstName;
    }

    public Person setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    public String getLastName() {
        return lastName;
    }

    public Person setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    public LocalDate getBirthDay() {
        return birthDay;
    }

    public Person setBirthDay(LocalDate birthDay) {
        this.birthDay = birthDay;
        return this;
    }

    public GenderType getGender() {
        return gender;
    }

    public Person setGender(GenderType gender) {
        this.gender = gender;
        return this;
    }

    public String getComment() {
        return comment;
    }

    public Person setComment(String comment) {
        this.comment = comment;
        return this;
    }

    public boolean isMarried() {
        return married;
    }

    public Person setMarried(boolean married) {
        this.married = married;
        return this;
    }

    public int getAge() {
        return age;
    }

    public Person setAge(int age) {
        this.age = age;
        return this;
    }

    public String getHomepage() {
        return homepage;
    }

    public Person setHomepage(String homepage) {
        this.homepage = homepage;
        return this;
    }
}
